### PR TITLE
Updated the Readme page

### PR DESCRIPTION
**Pull request by sahil290791**
Have updated readme page with new markdown.

### CODE REVIEW

**Comment by cainlevy** [comment]
@sahil290791 i'm sorry this got closed! would be happy to merge a `README.md`.

**Comment by sahil290791** [comment]
Hi, I was bit confused that in which repo I should open this merge request. I have reopened it again.

**Comment by sahil290791** [comment]
@cainlevy I have fixed the conflict in README.MD file.

**Comment by cainlevy** [comment]
thanks @sahil290791 🎊

**Pull request merged**
